// <auto-generated />
using DataAnalyze.Net.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAnalyse.Net.Migrations
{
    [DbContext(typeof(TelecomRecordContext))]
    partial class TelecomRecordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DataAnalyze.Net.Entity.TelecomRecord", b =>
                {
                    b.Property<int>("CallerFlag")
                        .HasColumnType("int");

                    b.Property<string>("CallerSite1")
                        .HasColumnType("longtext");

                    b.Property<string>("CallerSite2")
                        .HasColumnType("longtext");

                    b.Property<string>("Offset1")
                        .HasColumnType("longtext");

                    b.Property<string>("Offset2")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone1")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone2")
                        .HasColumnType("longtext");

                    b.Property<int>("TimeSpan")
                        .HasColumnType("int");

                    b.Property<int>("TimeStamp")
                        .HasColumnType("int");

                    b.ToTable("TelecomRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
